name: automerge check

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.8.3"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_FORKS: "true"
