name: automerge

on:
  pull_request_target:
    branches:
      - main

jobs:
  merge-me:
    permissions: write-all
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
